// Kadim Elfler - 20 Elf Temalı Maden ve Cevher Veritabanı
// Kural: Madenlerin süresi 10 dakika (600 saniye) sabit

export const MINING_DURATION_SECONDS = 600; // 10 Dakika Sabit (600 saniye)

export const ELVEN_MINES = [
  {
    id: 1,
    name: 'Ay Gümüşü',
    title: 'Gümüş Işıltılı Damar',
    level: 1,
    cardImage: '/assets/mines/mine_1.svg',
    oreImage: '/assets/ores/ore_1.svg',
    minGold: 1800,
    maxGold: 3200,
    minExp: 4500,
    maxExp: 7500,
    minOreYield: 1,
    maxOreYield: 3,
    sellPrice: 1200,
    rarity: 'Yaygın',
    lore: 'Dolunay ışığını emmiş saf gümüş cevheri. Elf zırhlarına büyü dayanıklılığı kazandırır.',
  },
  {
    id: 2,
    name: 'Yıldız Kristali',
    title: 'Göksel Işık Kümeleri',
    level: 5,
    cardImage: '/assets/mines/mine_2.svg',
    oreImage: '/assets/ores/ore_2.svg',
    minGold: 2600,
    maxGold: 4500,
    minExp: 6500,
    maxExp: 10500,
    minOreYield: 1,
    maxOreYield: 3,
    sellPrice: 1800,
    rarity: 'Nadir',
    lore: 'Gece göğünden düşen yıldızların parçalarından oluşan parlak gök kristali.',
  },
  {
    id: 3,
    name: 'Kadim Orman Cevheri',
    title: 'Köklerin Yeşil Cevheri',
    level: 10,
    cardImage: '/assets/mines/mine_3.svg',
    oreImage: '/assets/ores/ore_3.svg',
    minGold: 3800,
    maxGold: 6200,
    minExp: 9000,
    maxExp: 14000,
    minOreYield: 1,
    maxOreYield: 3,
    sellPrice: 2500,
    rarity: 'Nadir',
    lore: 'Bin yıllık meşe ağaçlarının derin kökleri arasında sıkışmış yeşil zümrüt damarı.',
  },
  {
    id: 4,
    name: 'Elf Çeliği',
    title: 'Mithril Alaşımlı Damar',
    level: 15,
    cardImage: '/assets/mines/mine_4.svg',
    oreImage: '/assets/ores/ore_4.svg',
    minGold: 5200,
    maxGold: 8500,
    minExp: 12500,
    maxExp: 18500,
    minOreYield: 1,
    maxOreYield: 3,
    sellPrice: 3400,
    rarity: 'Nadir',
    lore: 'Hafifliği tüy gibi, sağlamlığı elmastan farksız olan kadim elf demircilerinin gözdesi.',
  },
  {
    id: 5,
    name: 'Gölge Yaprağı Madeni',
    title: 'Obsidyen Yaprak Kanyonu',
    level: 20,
    cardImage: '/assets/mines/mine_5.svg',
    oreImage: '/assets/ores/ore_5.svg',
    minGold: 7000,
    maxGold: 11000,
    minExp: 16500,
    maxExp: 24000,
    minOreYield: 1,
    maxOreYield: 3,
    sellPrice: 4500,
    rarity: 'Destansı',
    lore: 'Karanlık vadilerde yaprak şeklinde billurlaşan keskin ve gizemli mor maden.',
  },
  {
    id: 6,
    name: 'Ay Tozu Cevheri',
    title: 'Işıltılı Jeot Galerisi',
    level: 25,
    cardImage: '/assets/mines/mine_6.svg',
    oreImage: '/assets/ores/ore_6.svg',
    minGold: 9200,
    maxGold: 14500,
    minExp: 21000,
    maxExp: 31000,
    minOreYield: 1,
    maxOreYield: 3,
    sellPrice: 5800,
    rarity: 'Destansı',
    lore: 'İçerisinde parıldayan ay tozu barındıran içi boş sedefli kadim taş.',
  },
  {
    id: 7,
    name: 'Yeşil Zümrüt',
    title: 'Kraliyet Zümrüt Damarı',
    level: 30,
    cardImage: '/assets/mines/mine_7.svg',
    oreImage: '/assets/ores/ore_7.svg',
    minGold: 12000,
    maxGold: 18500,
    minExp: 27000,
    maxExp: 39000,
    minOreYield: 1,
    maxOreYield: 3,
    sellPrice: 7500,
    rarity: 'Destansı',
    lore: 'Kusursuz sekizgen fasetli zümrüt kristali. Elf kolyeleri ve taçlarının baş tacıdır.',
  },
  {
    id: 8,
    name: 'Şafak Taşı',
    title: 'Güneş Işığı Ocağı',
    level: 35,
    cardImage: '/assets/mines/mine_8.svg',
    oreImage: '/assets/ores/ore_8.svg',
    minGold: 15500,
    maxGold: 23500,
    minExp: 34000,
    maxExp: 49000,
    minOreYield: 1,
    maxOreYield: 3,
    sellPrice: 9500,
    rarity: 'Destansı',
    lore: 'Sabahın ilk ışıklarını hapseden sıcak turuncu-altın rengi kor kristal.',
  },
  {
    id: 9,
    name: 'Orman Kalbi Cevheri',
    title: 'Yeşim Yaşam Kaynağı',
    level: 40,
    cardImage: '/assets/mines/mine_9.svg',
    oreImage: '/assets/ores/ore_9.svg',
    minGold: 19500,
    maxGold: 29500,
    minExp: 42000,
    maxExp: 60000,
    minOreYield: 1,
    maxOreYield: 3,
    sellPrice: 12000,
    rarity: 'Efsanevi',
    lore: 'Ormanın kalp atışıyla titreşen, dokunulduğunda yaşam enerjisi yayan yeşim taşı.',
  },
  {
    id: 10,
    name: 'Gümüş Yaprak Madeni',
    title: 'Platin Sarmaşık Yatağı',
    level: 45,
    cardImage: '/assets/mines/mine_10.svg',
    oreImage: '/assets/ores/ore_10.svg',
    minGold: 24500,
    maxGold: 36500,
    minExp: 51000,
    maxExp: 73000,
    minOreYield: 1,
    maxOreYield: 3,
    sellPrice: 15000,
    rarity: 'Efsanevi',
    lore: 'Taşın yüzeyinde gümüş sarmaşık yaprakları şeklinde büyüyen nadide platin minerali.',
  },
  {
    id: 11,
    name: 'Ay Işığı Kristali',
    title: 'Turkuaz Dikilitaş Damarı',
    level: 50,
    cardImage: '/assets/mines/mine_11.svg',
    oreImage: '/assets/ores/ore_11.svg',
    minGold: 30000,
    maxGold: 45000,
    minExp: 62000,
    maxExp: 88000,
    minOreYield: 1,
    maxOreYield: 3,
    sellPrice: 19000,
    rarity: 'Efsanevi',
    lore: 'Karanlık sularda parlayan dikilitaş şeklindeki saf turkuaz ay kristali.',
  },
  {
    id: 12,
    name: 'Kadim Ağaç Reçinesi',
    title: 'Kehribar Gözyaşı Yatağı',
    level: 55,
    cardImage: '/assets/mines/mine_12.svg',
    oreImage: '/assets/ores/ore_12.svg',
    minGold: 36500,
    maxGold: 54500,
    minExp: 75000,
    maxExp: 105000,
    minOreYield: 1,
    maxOreYield: 3,
    sellPrice: 24000,
    rarity: 'Efsanevi',
    lore: 'İlk çağlardan beri katılaşmış, içinde parıldayan kadim elf yaprağını koruyan kehribar.',
  },
  {
    id: 13,
    name: 'Yıldız Tozu Cevheri',
    title: 'Galaksi Yarığı Ocağı',
    level: 60,
    cardImage: '/assets/mines/mine_13.svg',
    oreImage: '/assets/ores/ore_13.svg',
    minGold: 44000,
    maxGold: 65000,
    minExp: 90000,
    maxExp: 125000,
    minOreYield: 1,
    maxOreYield: 3,
    sellPrice: 30000,
    rarity: 'Efsanevi',
    lore: 'Mor nebulalar gibi parıldayan, içerisinde binlerce minik yıldız kıvılcımı barındıran taş.',
  },
  {
    id: 14,
    name: 'Elf Büyü Kristali',
    title: 'Çift Arcane Sütunları',
    level: 65,
    cardImage: '/assets/mines/mine_14.svg',
    oreImage: '/assets/ores/ore_14.svg',
    minGold: 53000,
    maxGold: 78000,
    minExp: 107000,
    maxExp: 148000,
    minOreYield: 1,
    maxOreYield: 3,
    sellPrice: 38000,
    rarity: 'Mitolojik',
    lore: 'Saf pembe ve mavi mana enerjisinden örülü, kendi etrafında dönen kadim büyü odağı.',
  },
  {
    id: 15,
    name: 'Gölge Gümüşü',
    title: 'Dumanlı Krom Uçurumu',
    level: 70,
    cardImage: '/assets/mines/mine_15.svg',
    oreImage: '/assets/ores/ore_15.svg',
    minGold: 63000,
    maxGold: 92000,
    minExp: 126000,
    maxExp: 174000,
    minOreYield: 1,
    maxOreYield: 3,
    sellPrice: 47000,
    rarity: 'Mitolojik',
    lore: 'Gölge diyarının soğuk metallerinden biri; ışığı yutar ve dokunanı görünmez kılar.',
  },
  {
    id: 16,
    name: 'Doğa Özü Madeni',
    title: 'Toprak ve Su Pınarı',
    level: 75,
    cardImage: '/assets/mines/mine_16.svg',
    oreImage: '/assets/ores/ore_16.svg',
    minGold: 74000,
    maxGold: 108000,
    minExp: 148000,
    maxExp: 203000,
    minOreYield: 1,
    maxOreYield: 3,
    sellPrice: 58000,
    rarity: 'Mitolojik',
    lore: 'Toprak, su ve rüzgar elementlerinin birleşiminden doğan turkuaz renkli yaşam tohumu.',
  },
  {
    id: 17,
    name: 'Kristal Yaprak Cevheri',
    title: 'Buzul Kuvars Yatağı',
    level: 80,
    cardImage: '/assets/mines/mine_17.svg',
    oreImage: '/assets/ores/ore_17.svg',
    minGold: 87000,
    maxGold: 126000,
    minExp: 173000,
    maxExp: 236000,
    minOreYield: 1,
    maxOreYield: 3,
    sellPrice: 70000,
    rarity: 'Mitolojik',
    lore: 'Kusursuz cam parlaklığında donmuş, ışığı prizmatik gökkuşağına ayıran kuvars yaprak.',
  },
  {
    id: 18,
    name: 'Ay Çiçeği Taşı',
    title: 'Safir Rozet Terası',
    level: 85,
    cardImage: '/assets/mines/mine_18.svg',
    oreImage: '/assets/ores/ore_18.svg',
    minGold: 102000,
    maxGold: 147000,
    minExp: 202000,
    maxExp: 274000,
    minOreYield: 1,
    maxOreYield: 3,
    sellPrice: 84000,
    rarity: 'Mitolojik',
    lore: 'Taşın içinde bir çiçek gibi açan lavanta ve safir rengi kristal yapraklar.',
  },
  {
    id: 19,
    name: 'Kadim Elf Demiri',
    title: 'Rünik Meteor Çukuru',
    level: 90,
    cardImage: '/assets/mines/mine_19.svg',
    oreImage: '/assets/ores/ore_19.svg',
    minGold: 120000,
    maxGold: 172000,
    minExp: 235000,
    maxExp: 318000,
    minOreYield: 1,
    maxOreYield: 3,
    sellPrice: 100000,
    rarity: 'Kadim Efsane',
    lore: 'Gökten düşen göktaşının kadim elf rünleriyle dövülmesiyle elde edilen nihai metal.',
  },
  {
    id: 20,
    name: 'Ebedi Orman Cevheri',
    title: 'Kutsal Yaratılış Taşı',
    level: 95,
    cardImage: '/assets/mines/mine_20.svg',
    oreImage: '/assets/ores/ore_20.svg',
    minGold: 145000,
    maxGold: 210000,
    minExp: 280000,
    maxExp: 380000,
    minOreYield: 2,
    maxOreYield: 4,
    sellPrice: 130000,
    rarity: 'Kadim Efsane',
    lore: 'Dünyanın kalbindeki ilk tohumdan kristalleşen, tüm canlılığın kutsal özünü taşıyan ulu cevher.',
  },
];

// Maden Kazı Sonucu Hesaplama
export function rollMiningRewards(mine) {
  // Rastgele Altın
  const gold = Math.floor(Math.random() * (mine.maxGold - mine.minGold + 1)) + mine.minGold;

  // Madenler EXP vermez (0 EXP - Seviye atlamak %100 zindanda canavar keserek sağlanır)
  const exp = 0;

  // Cevher Miktarı (1 - 3 adet)
  const oreCount = Math.floor(Math.random() * (mine.maxOreYield - mine.minOreYield + 1)) + mine.minOreYield;

  const droppedOres = [];
  for (let i = 0; i < oreCount; i++) {
    droppedOres.push({
      id: `ore_${mine.id}`,
      instanceId: `ore_${mine.id}_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
      name: mine.name,
      setName: 'Kadim Elf Madeni',
      className: 'Zanaat & Maden',
      slot: 'ore',
      slotName: 'Cevher & Materyal',
      type: 'ore',
      isOre: true,
      rarity: mine.rarity,
      levelMin: mine.level,
      levelMax: 100,
      image: mine.oreImage,
      sellPrice: mine.sellPrice,
      desc: mine.lore,
      droppedAt: new Date().toISOString(),
    });
  }

  return {
    gold,
    exp,
    droppedOres,
  };
}
